---
- name: 'Load distribution specific settings for nginx'
  include_vars: '{{ var_file }}'
  failed_when: false
  loop_control:
    loop_var: 'var_file'
  loop:
    - 'vars/{{ ansible_os_family | lower }}.yml'
    - 'vars/{{ ansible_distribution | lower }}.yml'
    - 'vars/{{ ansible_distribution | lower }}{{ ansible_distribution_major_version }}.yml'
    - 'vars/{{ ansible_distribution | lower }}{{ ansible_distribution_version }}.yml'
    #  |  debian.yml
    #  |  ubuntu.yml
    #  |  ubuntu18.yml
    #  v  ubuntu18.04.yml

- name: 'Disable SELinux'
  selinux:
    state: 'disabled'
  when: 'ansible_distribution == "rhel" or ansible_distribution == "redhat"'

- name: 'Install nginx'
  package:
    name:  '{{ nginx_pkgs }}'
    state: 'present'

- name: 'Enable & start nginx'
  service:
    name:    '{{ nginx_service }}'
    enabled: '{{ nginx_enabled | bool }}'
    state:   'started'

- name: 'Configure nginx via nginx.conf'
  template:
    src:   'nginx.conf.j2'
    dest:  '/etc/nginx/nginx.conf'
    owner: 'root'
    group: 'root'
    mode:  '0644'
  notify: 'Restart nginx'
...
